In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler

from time import sleep
import datetime

dataset1(19.9.11 20:00:00 ~ 19.9.15 09:59:59)<br>
testset1(19.10.29 11:00:00 ~ 19.11.01 19:59:59)<br>
dataset2(19.11.01 20:00:00 ~ 19.11.04 14:59:59)<br>
testset2(19.11.04 15:00:00 ~ 19.11.06 9:29:59)

In [172]:
testset1 = pd.read_csv('HAI 1.0/test-dataset/test1.csv', parse_dates=['time']).set_index('time')
testset2 = pd.read_csv('HAI 1.0/test-dataset/test2.csv', parse_dates=['time']).set_index('time')

In [173]:
testset1.head(1)

P1_B2004  P1_B2016  P1_B3004   P1_B3005  P1_B4002  \
time                                                                     
2019-10-29 11:00:00    0.0982     1.461  461.9883  1099.7363      32.0   

                     P1_B4005  P1_B400B  P1_B4022  P1_FCV01D  P1_FCV01Z  ...  \
time                                                                     ...   
2019-10-29 11:00:00       0.0  113.4112    35.907     9.2526     9.7824  ...   

                     P4_ST_FD  P4_ST_LD  P4_ST_PO  P4_ST_PS  P4_ST_PT01  \
time                                                                      
2019-10-29 11:00:00   -0.0027  355.4688  349.6998       0.0     10053.0   

                     P4_ST_TT01  attack  attack_P1  attack_P2  attack_P3  
time                                                                      
2019-10-29 11:00:00     27629.0       0          0          0          0  

[1 rows x 63 columns]

In [174]:
testset2.head(1)

P1_B2004  P1_B2016  P1_B3004   P1_B3005  P1_B4002  \
time                                                                     
2019-11-04 15:00:00    0.1001     1.527  395.3508  1120.8154   29.4139   

                     P1_B4005  P1_B400B  P1_B4022  P1_FCV01D  P1_FCV01Z  ...  \
time                                                                     ...   
2019-11-04 15:00:00       0.0   32.9705   33.4784        0.0     0.2609  ...   

                     P4_ST_FD  P4_ST_LD  P4_ST_PO  P4_ST_PS  P4_ST_PT01  \
time                                                                      
2019-11-04 15:00:00   -0.0009  366.8258  364.7823       0.0     10026.0   

                     P4_ST_TT01  attack  attack_P1  attack_P2  attack_P3  
time                                                                      
2019-11-04 15:00:00     27549.0       0          0          0          0  

[1 rows x 63 columns]

In [175]:
scaler = MinMaxScaler()
testset1[testset1.columns[:-4]] = scaler.fit_transform(testset1[testset1.columns[:-4]])
testset2[testset2.columns[:-4]] = scaler.fit_transform(testset2[testset2.columns[:-4]])

In [176]:
testset1.head(1)

P1_B2004  P1_B2016  P1_B3004  P1_B3005  P1_B4002  \
time                                                                    
2019-10-29 11:00:00  0.949509  0.583314  0.863839  0.901928       1.0   

                     P1_B4005  P1_B400B  P1_B4022  P1_FCV01D  P1_FCV01Z  ...  \
time                                                                     ...   
2019-10-29 11:00:00       0.0  0.031333  0.778295   0.092526   0.094568  ...   

                     P4_ST_FD  P4_ST_LD  P4_ST_PO  P4_ST_PS  P4_ST_PT01  \
time                                                                      
2019-10-29 11:00:00  0.502503   0.66909   0.58316       0.0    0.021381   

                     P4_ST_TT01  attack  attack_P1  attack_P2  attack_P3  
time                                                                      
2019-10-29 11:00:00         1.0       0          0          0          0  

[1 rows x 63 columns]

In [177]:
testset2.head(1)

P1_B2004  P1_B2016  P1_B3004  P1_B3005  P1_B4002  \
time                                                                    
2019-11-04 15:00:00  0.977685  0.613739  0.021004  0.999752       0.0   

                     P1_B4005  P1_B400B  P1_B4022  P1_FCV01D  P1_FCV01Z  ...  \
time                                                                     ...   
2019-11-04 15:00:00       0.0  0.006942  0.236188        0.0   0.000151  ...   

                     P4_ST_FD  P4_ST_LD  P4_ST_PO  P4_ST_PS  P4_ST_PT01  \
time                                                                      
2019-11-04 15:00:00  0.485577  0.516198  0.549594       0.0    0.529674   

                     P4_ST_TT01  attack  attack_P1  attack_P2  attack_P3  
time                                                                      
2019-11-04 15:00:00    0.641256       0          0          0          0  

[1 rows x 63 columns]

In [ ]:
attack_P1, P1
['P1_FCV03D','P1_FCV03Z','P1_FT01','P1_FT01Z','P1_LCV01D','P1_LCV01Z','P1_PCV01D','P1_PCV01Z','P1_PIT01','P1_TIT01']
attack_P2, P2
['P2_SIT01','P2_VT01e','P2_VXT02','P2_VXT03','P2_VYT02','P2_VYT03']
attack_P3, P3
['P3_LCP01D']
attack_P1, P4
['P4_ST_PT01']

In [147]:
corr = extract.corr()
corr.attack.sort_values(ascending=False)

attack        1.000000
P1_LCV01D     0.244757
P1_LCV01Z     0.234201
P1_FT01       0.120438
P2_VXT03      0.083935
P1_FCV03D     0.076803
P1_FCV03Z     0.071992
P2_VYT03      0.059328
P2_VXT02      0.048502
P2_VYT02      0.042249
P3_LCP01D     0.029564
P2_VT01e      0.021973
P1_PCV01Z    -0.037095
P1_PCV01D    -0.038175
P1_TIT01     -0.044420
P1_FT01Z     -0.048789
P4_ST_PT01   -0.071041
P1_PIT01     -0.108248
P2_SIT01     -0.279366
Name: attack, dtype: float64

In [149]:
extract1 = testset1.copy()
extract1 = extract1[['P1_FCV03D','P1_FCV03Z','P1_FT01','P1_FT01Z','P1_LCV01D','P1_LCV01Z','P1_PCV01D','P1_PCV01Z','P1_PIT01','P1_TIT01',
'P2_SIT01','P2_VT01e','P2_VXT02','P2_VXT03','P2_VYT02','P2_VYT03','P3_LCP01D','P4_ST_PT01','attack']]
extract2 = testset2.copy()
extract2 = extract2[['P1_FCV03D','P1_FCV03Z','P1_FT01','P1_FT01Z','P1_LCV01D','P1_LCV01Z','P1_PCV01D','P1_PCV01Z','P1_PIT01','P1_TIT01',
'P2_SIT01','P2_VT01e','P2_VXT02','P2_VXT03','P2_VYT02','P2_VYT03','P3_LCP01D','P4_ST_PT01','attack']]

### 데이터셋 나누기

In [150]:
trainset = extract1.copy()
features = trainset.drop('attack', axis=1)
labels = trainset['attack']

predset = extract2.copy()
preds = predset.drop('attack', axis=1)
pred_label = predset['attack']

np.shape(features), np.shape(labels), np.shape(preds), np.shape(pred_label)

((291600, 18), (291600,), (153000, 18), (153000,))

In [151]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.dummy import DummyClassifier

In [152]:
dummy = DummyClassifier(strategy='most_frequent').fit(features, labels)
pred_dummy = dummy.predict(preds)

In [153]:
# decision tree 로 모델링
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=5, random_state=0); tree.fit(features, labels)
pred_tree = tree.predict(preds); print(classification_report(pred_label, pred_tree))
print("-----------------------------------")
print("Dummy model:"); print(confusion_matrix(pred_label, pred_dummy))
print("Decision tree:"); print(confusion_matrix(pred_label, pred_tree))

precision    recall  f1-score   support

           0       0.89      0.14      0.24    147011
           1       0.03      0.60      0.05      5989

    accuracy                           0.16    153000
   macro avg       0.46      0.37      0.15    153000
weighted avg       0.86      0.16      0.23    153000

-----------------------------------
Dummy model:
[[147011      0]
 [  5989      0]]
Decision tree:
[[ 20407 126604]
 [  2412   3577]]


In [156]:
from imblearn.combine import SMOTETomek
X_resampled, y_resampled = SMOTETomek(random_state=0).fit_sample(features, labels)
print(X_resampled.shape, features.shape, y_resampled.shape, labels.shape)

Using TensorFlow backend.
(560072, 18) (291600, 18) (560072,) (291600,)


NameError: name 'pred_labels' is not defined

In [161]:
dummy = DummyClassifier(strategy='most_frequent').fit(X_resampled, y_resampled)
pred_dummy = dummy.predict(preds)

In [162]:
# decision tree 로 모델링
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=5, random_state=0)
tree.fit(X_resampled, y_resampled)
pred_tree = tree.predict(preds)

print(classification_report(pred_label, pred_tree))
print("-----------------------------------")
print("Dummy model:"); print(confusion_matrix(pred_label, pred_dummy))
print("Decision tree:"); print(confusion_matrix(pred_label, pred_tree))

precision    recall  f1-score   support

           0       0.98      0.13      0.23    147011
           1       0.04      0.92      0.08      5989

    accuracy                           0.16    153000
   macro avg       0.51      0.53      0.16    153000
weighted avg       0.94      0.16      0.23    153000

-----------------------------------
Dummy model:
[[147011      0]
 [  5989      0]]
Decision tree:
[[ 19613 127398]
 [   459   5530]]
